Repository operate-first/operate-first-in-action, pull requests merged in 2022-05, with the labels that each got.

#14 update op1st content
  README.md
Labels: size/S, approved, lgtm

#16 changed dummy video to real video
  README.md
Labels: approved, size/XS, lgtm

#18 finalizing Readme
  README.md
  assets/images/jupyter-notebook.png
  assets/images/jupyterhub-spawner.png
  assets/images/meteor-integration.png
Labels: approved, lgtm, size/M

#19 Added BYON image and link
  README.md
  assets/images/byon.png
  assets/images/meteor.png
Labels: approved, size/XS, lgtm

#20 Add google analytics id
  _config.yml
Labels: approved, size/XS, lgtm

#21 update copyright date
  _config.yml
Labels: approved, size/XS, lgtm

#22 added instructions on adding oneself to operate first
  README.md
Labels: approved, size/XS, lgtm

#23 Update _config.yml
  _config.yml
Labels: approved, size/XS, lgtm

#24 Update _config.yml (#23)
  _config.yml
Labels: approved, size/XS, lgtm
